### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by worthy7** [chekit/xlf2xlf#4]
```
X Something went wrong while translating messages.xlf!
TypeError: Cannot read property 'forEach' of undefined
    at translate (C:\Users\worth\AppData\Roaming\npm\node_modules\xlf2xlf\src\translate.js:46:33)
    at C:\Users\worth\AppData\Roaming\npm\node_modules\xlf2xlf\src\index.js:82:16
```

Angular 9 & 17

**Comment by chekit** [comment]
Hi, can you share the .xlf file?

**Comment by worthy7** [comment]
```
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" target-language="ja" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="e4b5b514aaee5b9402cccb2b461f97ac6e1e44f0" datatype="html">
        <source>Audit Log</source>
        <target state="new">Audit Log</target>
        <context-group purpose="location">
          <context context-type="sourcefile">
            projects/home/src/app/admin-auditlog-list/admin-auditlog-list.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
        <context-group purpose="location">
          <context context-type="sourcefile">
            projects/home/src/app/admin-users/admin-users.component.html</context>
          <context context-type="linenumber">229</context>
        </context-group>
      </trans-unit>
      <trans-unit id="ae011766f54d345ad7304e2fc4ca6d5286ac3afb" datatype="html">
        <source>Background jobs</source>
        <target state="new">Background jobs</target>
        <context-group purpose="location">
          <context context-type="sourcefile">
            projects/home/src/app/admin-backgroundjobs-list/admin-backgroundjobs-list.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
</body>
  </file>
</xliff>
```

**Comment by chekit** [comment]
That strange as I tried to translate your file 3 times locally, with npx and installing xlf2xlf package globally and all the times it gives no error:

```shell
$ node ./src/index.js --in test.xlf --out test.nl.xlf --from en --to nl
Translating Background jobs to Achtergrondopdrachten
Translating Audit Log to Auditlogboek
✓ Finished translating test.xlf in 3033ms.
```

```shell
$ npx xlf2xlf --in test.xlf --out test.nl.xlf --from en --to nl
Need to install the following packages:
  xlf2xlf
Ok to proceed? (y) y
Translating Audit Log to Auditlogboek
Translating Background jobs to Achtergrondopdrachten
✓ Finished translating test.xlf in 1720ms.
```

```shell
$ xlf2xlf --in test.xlf --out test.de.xlf --from en --to de
Translating Background jobs to Hintergrundjobs
Translating Audit Log to Audit-Log
✓ Finished translating test.xlf in 2528ms.
```

This is the results:

> test.nl.xlf

```xml
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="en-US" target-language="nl" datatype="plaintext" original="ng2.template" date="2024-01-06T14:36:59Z">
        <body>
            <trans-unit id="e4b5b514aaee5b9402cccb2b461f97ac6e1e44f0" datatype="html">
                <source>Audit Log</source>
                <target state="new">Audit Log</target>
                <context-group purpose="location">
                    <context context-type="sourcefile">
            projects/home/src/app/admin-auditlog-list/admin-auditlog-list.component.html</context>
                    <context context-type="linenumber">1</context>
                </context-group>
                <context-group purpose="location">
                    <context context-type="sourcefile">
            projects/home/src/app/admin-users/admin-users.component.html</context>
                    <context context-type="linenumber">229</context>
                </context-group>
                <target>Auditlogboek</target>
            </trans-unit>
            <trans-unit id="ae011766f54d345ad7304e2fc4ca6d5286ac3afb" datatype="html">
                <source>Background jobs</source>
                <target state="new">Background jobs</target>
                <context-group purpose="location">
                    <context context-type="sourcefile">
            projects/home/src/app/admin-backgroundjobs-list/admin-backgroundjobs-list.component.html</context>
                    <context context-type="linenumber">1</context>
                </context-group>
                <target>Achtergrondopdrachten</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```

> test.de.xlf
```xml
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="en-US" target-language="de" datatype="plaintext" original="ng2.template" date="2024-01-06T14:41:12Z">
        <body>
            <trans-unit id="e4b5b514aaee5b9402cccb2b461f97ac6e1e44f0" datatype="html">
                <source>Audit Log</source>
                <target state="new">Audit Log</target>
                <context-group purpose="location">
                    <context context-type="sourcefile">
            projects/home/src/app/admin-auditlog-list/admin-auditlog-list.component.html</context>
                    <context context-type="linenumber">1</context>
                </context-group>
                <context-group purpose="location">
                    <context context-type="sourcefile">
            projects/home/src/app/admin-users/admin-users.component.html</context>
                    <context context-type="linenumber">229</context>
                </context-group>
                <target>Audit-Log</target>
            </trans-unit>
            <trans-unit id="ae011766f54d345ad7304e2fc4ca6d5286ac3afb" datatype="html">
                <source>Background jobs</source>
                <target state="new">Background jobs</target>
                <context-group purpose="location">
                    <context context-type="sourcefile">
            projects/home/src/app/admin-backgroundjobs-list/admin-backgroundjobs-list.component.html</context>
                    <context context-type="linenumber">1</context>
                </context-group>
                <target>Hintergrundjobs</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```

**Comment by worthy7** [comment]
```
      <trans-unit id="4416290763660062288" datatype="html">
        <source />
        <context-group purpose="location">
          <context context-type="sourcefile">
            projects/home/src/app/landing-page/pages/zoom/zoom.component.ts</context>
          <context context-type="linenumber">46</context>
        </context-group>
        <context-group purpose="location">
          <context context-type="sourcefile">
            projects/home/src/app/landing-page/pages/zoom/zoom.component.ts</context>
          <context context-type="linenumber">47</context>
        </context-group>
      </trans-unit>
```

It took some time to narrow it down (binary search on the file) but the reason is that it crashes when there is no source. Could you make the error message nicer or make it handle this case and just make a target with nothing in it for consistency?

**Comment by chekit** [comment]
> ```
>       <trans-unit id="4416290763660062288" datatype="html">
>         <source />
>         <context-group purpose="location">
>           <context context-type="sourcefile">
>             projects/home/src/app/landing-page/pages/zoom/zoom.component.ts</context>
>           <context context-type="linenumber">46</context>
>         </context-group>
>         <context-group purpose="location">
>           <context context-type="sourcefile">
>             projects/home/src/app/landing-page/pages/zoom/zoom.component.ts</context>
>           <context context-type="linenumber">47</context>
>         </context-group>
>       </trans-unit>
> ```
> 
> It took some time to narrow it down (binary search on the file) but the reason is that it crashes when there is no source. Could you make the error message nicer or make it handle this case and just make a target with nothing in it for consistency?

The fix will be applied shortly

**Comment by chekit** [comment]
I have released version `1.2.0` that contains fixes for such a case.
